version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - nouda
  ignore:
  - dependency-name: net.java.dev.javacc:javacc
    versions:
    - "> 4.0"
  - dependency-name: org.jgroups:jgroups
    versions:
    - "> 4.0.20.Final"
  - dependency-name: io.micrometer:micrometer-registry-influx
    versions:
    - 1.6.3
    - 1.6.4
    - 1.6.5
  - dependency-name: io.micrometer:micrometer-core
    versions:
    - 1.6.3
    - 1.6.4
    - 1.6.5
  - dependency-name: io.micrometer:micrometer-registry-jmx
    versions:
    - 1.6.3
    - 1.6.4
    - 1.6.5
  - dependency-name: io.micrometer:micrometer-registry-prometheus
    versions:
    - 1.6.3
    - 1.6.4
    - 1.6.5
  - dependency-name: com.adarshr:gradle-test-logger-plugin
    versions:
    - 2.1.1
  - dependency-name: org.hsqldb:hsqldb
    versions:
    - 2.5.1
