name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ubuntu:
    name: Ubuntu (JDK ${{ matrix.java }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [8, 11, 13]
    steps:
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        chmod +x ./gradlew
        ./gradlew --no-daemon build

  windows:
    name: Windows (JDK ${{ matrix.java }})
    runs-on: windows-2019
    strategy:
      matrix:
        java: [8, 11, 13]
    steps:
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      shell: cmd
      run: |
        ./gradlew --no-daemon build
